import 'bootstrap-icons/icons/chevron-left.svg';
import 'bootstrap-icons/icons/chevron-right.svg';
import 'bootstrap-icons/icons/three-dots.svg';
import 'bootstrap-icons/icons/list.svg';
import 'bootstrap-icons/icons/arrow-up-circle.svg';
import 'bootstrap-icons/icons/sun-fill.svg';
import 'bootstrap-icons/icons/slash.svg';
import 'bootstrap-icons/icons/cloud-arrow-up.svg';
import 'bootstrap-icons/icons/pencil.svg';
import 'bootstrap-icons/icons/pencil-square.svg';
import 'bootstrap-icons/icons/clipboard.svg';
import 'bootstrap-icons/icons/clipboard-check.svg';
import 'bootstrap-icons/icons/trash.svg';
import 'bootstrap-icons/icons/plus-circle.svg';
import './loading.svg';

export type IconID =
  | 'loading'
  | 'chevron-left'
  | 'chevron-right'
  | 'three-dots'
  | 'list'
  | 'arrow-up'
  | 'arrow-up-circle'
  | 'sun-fill'
  | 'slash'
  | 'cloud-arrow-up'
  | 'pencil'
  | 'pencil-square'
  | 'clipboard'
  | 'clipboard-check'
  | 'trash'
  | 'plus-circle';
